services:
  db:
    image: postgres:15-alpine
    container_name: ts_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ts_db
    ports:
      - "5446:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: